export const STATUS = {
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
};

export const TRANSACTION_TYPE = {
  DEPOSIT: "DEPOSIT",
  WITHDRAWAL: "WITHDRAWAL",
  REFUND: "REFUND",
};

export const PAYMENT_METHOD = {
  BANK_TRANSFER: "BANK_TRANSFER",
  E_WALLET: "E_WALLET",
  CASH: "CASH",
};

export const PICKUP_METHOD = {
  PICKUP: "PICKUP",
  DROPOFF: "DROPOFF",
};

export const USER_ROLE = {
  USER: "USER",
  ADMIN: "ADMIN",
};
